name: Deployment using container
on:
  push:
    branches:
      - main
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:16
    steps:
      - name: Install & cache dependencies
        uses: ./.github/actions/install-and-cache
      - name: Test project
        run: npm run test
      - name: Ouput information
        run: echo "Project tested successfully!!"
