name: Deployment matrix
on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - ".github/workflows/*"
jobs:
  build:
    strategy:
      matrix:
        nv: [12, 14, 16]
        os: [ubuntu-latest, windows-latest]
        include:
          - nv: 18
            os: ubuntu-latest
        exclude:
          - nv: 12
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get project
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.nv }}
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
