name: Deployment
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install yarn globally
        run: npm install -g yarn
      - name: Get project
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install
      - name: Test project
        run: yarn test
      - name: Build project
        run: yarn build
      - name: Deploy project
        run: echo "Deployed successfully!!"
