name: Deployment Parallel
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - closed
    branches:
      - main
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install yarn
        run: npm install -g yarn
      - name: Get project
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install
      - name: Test project
        run: yarn test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install yarn
        run: npm install -g yarn
      - name: Get project
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install
      - name: Build project
        run: yarn build
      - name: Deploy project
        run: echo "Deployed.."
