name: Deployment reusable
on:
  workflow_call:
    inputs:
      artifact:
        description: The arifact file identifier name
        required: false
        default: build
        type: string
    outputs:
      result:
        description: Store the result of the deployment
        value: ${{ jobs.deploy.outputs.outcome }}
jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-output-runner.outputs.result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact }}
      - name: Artifact content
        run: ls
      - name: Project deploy
        run: echo "Project deployment completed successfully!!"
      - name: Set outputs
        id: set-output-runner
        run: echo "result=success" >> @GITHUB_OUTPUT
