name: Push Deployment
on: push
jobs:
  push-request:
    runs-on: ubuntu-latest
    steps:
      - name: Install 'yarn' globally
        run: npm install -g yarn
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install
      - name: Test code
        run: yarn test
      - name: Build project
        run: yarn build
      - name: Deploy project
        run: echo "Deployed successfully!!"
